### ISSUE TITLE
Not parsing u-repost-of in some cases

### ISSUE THREAD

**Issue by singpolyma** [indieweb/php-mf2#173]
https://pin13.net/mf2/?url=http%3A%2F%2Fbeta.singpolyma.net%2F_ipfs%2FL25vdGVzLzIwMTgwOTYgcnQtaHR0cHN0d2l0dGVyLWNvbW1pbm5lYXBvbGlzZmVkc3RhdHVzOTgxNTU3NjcwMjE2ODU5NjQ4LW1pbm5lYXBvbGlzLWZlZC9pbmRleC5odG1s%2Frt-httpstwitter-comminneapolisfedstatus981557670216859648-minneapolis-fed%2F

does not show the `repost-of` property

https://python.microformats.io/?url=http%3A%2F%2Fbeta.singpolyma.net%2F_ipfs%2FL25vdGVzLzIwMTgwOTYgcnQtaHR0cHN0d2l0dGVyLWNvbW1pbm5lYXBvbGlzZmVkc3RhdHVzOTgxNTU3NjcwMjE2ODU5NjQ4LW1pbm5lYXBvbGlzLWZlZC9pbmRleC5odG1s%2Frt-httpstwitter-comminneapolisfedstatus981557670216859648-minneapolis-fed%2F&parser=html5lib

does

**Comment by aaronpk** [comment]
This was a recent change to the PHP parser which should eventually be adopted by the rest of them.

There is no `h-entry` class on your post, just the mf1 `hentry`. The improved backcompat parsing rules say to ignore mf2 classes on mf1 objects to reduce the error rates that we were seeing. If you change `hentry` to `h-entry` and use mf2 class names everywhere then it'll be picked up properly.

**Comment by Zegnat** [comment]
Putting the HTML of that post into @kartikprabhu’s [development version](https://kartikprabhu.com/connection/mfparser) of the Python parser will also not return the `repost-of`. As there has just been a new release of that parser yesterday, an update to `python.microformats.io` might be necessary.

**Comment by singpolyma** [comment]
Oof... that's a pretty serious breaking change to back-compat :(

**Comment by aaronpk** [comment]
It's more a correction to the parsers, the intent of backcompat hasn't changed. The backcompat rules were never intended to mix mf2 and mf1 properties, but they were accidentally implemented in the parsers that way. The backcompat algorithm was updated to reflect this recently, and the parsers have started to make the change. Mixing mf1 and mf2 is not a good idea since it really just confuses everyone involved, unless maybe you're so used to mf1 that it actually makes sense to you. I'm glad we're finally sorting this out and deprecating the mf1 syntax except for very specific legacy use cases.

**Comment by gRegorLove** [comment]
I'm closing this since the behavior is correct according to the spec and php-mf2, mf2py implement it now.
