### ISSUE TITLE
Implement microformats test suite

### ISSUE THREAD

**Issue by gRegorLove** [indieweb/php-mf2#50]
@barnabywalters mentioned php-mf2 should run tests against the microformats test suite: https://github.com/tobiastom/tests. I have volunteered to take on this task.

**Comment by aaronpk** [comment]
It looks like the original test suite (https://github.com/microformats/tests) was updated so that this library can use it directly, instead of using the forked tobiastom version. Note the comment here: https://github.com/tobiastom/tests/issues/2#issuecomment-108883795

I would suggest we reference the main microformats/tests repo instead, ideally by publishing that repo to composer and bringing it in to here that way.

**Comment by gRegorLove** [comment]
I've got this working on my fork of php-mf2. I have a [PR open](https://github.com/microformats/tests/pull/47) to add composer.json to microformats/test so it can be included here. Once that's accepted, I'll submit the test-suite PR for php-mf2.

**Comment by gRegorLove** [comment]
Completed with #95.
