### ISSUE TITLE
classes on `<body>` are ignored

### ISSUE THREAD

**Issue by dym-cx** [indieweb/php-mf2#68]
used html from https://gist.github.com/dym-cx/a7fdb47dc6d2fc076496

**Comment by barnabywalters** [comment]
Sorry for the delay dealing with this issue! I just took a proper look, and the issue seems to be stemming from the fact that your <html> element is spelled incorrectly, as <hmtl>. Running your code through https://waterpigs.co.uk/php-mf2/ with a corrected <html> element results in correct parsing.

Handling of root classnames should be tag-independent, so this is still an issue for php-mf2. I suspect it is an internal issue with DOMDocument refusing to correctly parse HTML documents with incorrect <html> elements. Until we can fix that though, you can achieve correct parsing of this example by correcting the <html> element :)
