### ISSUE TITLE
releative srcset urls do not get resolved to absolute urls

### ISSUE THREAD

**Issue by diplix** [indieweb/php-mf2#78]
[resolveChildUrls()](https://github.com/indieweb/php-mf2/blob/9a5464e0b913ba59f175d87b6950092660f06878/Mf2/Parser.php#L331) takes good care of resolving relative urls in href, src and data attributes. however srcset is left out and image urls in it are left unresolved — which causes problems for indiewebreaders that show broken images if the srcset attribute is used.

**Comment by barnabywalters** [comment]
Hmm, in order to fix this issue, php-mf2 would have to include a srcset parser and serialiser. I can’t find either already built in PHP, which means we have to roll our own. Here’s a prose description of the format, I can’t easily find a prose parsing algorithm (@tantek, any ideas where that could be found?) https://developers.whatwg.org/edits.html#attr-img-srcset

Anyone want to take a look at implementing this?

**Comment by diplix** [comment]
indeed not easy to find a php parser for srcset. all i found is found a javascript version:
https://github.com/sindresorhus/srcset

**Comment by voxpelli** [comment]
It would be fairly simple to parse it I think, here's an example: https://gist.github.com/voxpelli/6a5dc3c8614ae8937527

Using the method from that example one could do:

```php
if ($child->hasAttribute('srcset'))
    $child->setAttribute('srcset', applySrcSetUrlTransformation($child->getAttribute('href'), [$this, resolveUrl]));
```

**Comment by diplix** [comment]
👍
